MauricioMVilcapoma/Netvision-OpenSource-WS51

- README.md
Added  startup-profile, startup-description and team profile.
> added startup-profile

- README.md
This is the description of our product called Eventify.
> added solution profile

- README.md
> added Antecedentes y problemática

- README.md
here are the Domain, Customer Segments, Pain Points, Gap, Vision/Strategy and Initial Segment for the Lean UX Process
> added problem-statements

- README.md
This sections shows or targets such as people who go to events.
> added Segmento objetivo

- README.md
This section analyze our direct competitors such as joinuss, teleticket and eventbrite
> added competidores

- README.md
this section is about the strategy we are gonna take about the competitors.
> added Estrategias y tácticas frente a competidores

- README.md
A Scenario Mapping was made for every user persona
> added Scenario Mapping

- README.md
Update the link for the images for the to be scenario mapping
> updated to-be-scenario-mapping

- README.md
Updated the format of the as-is-scenario-mapping using the UXPRESSIA tool
> updated as-is-scenario-mapping

- README.md
> added Impact-mapping

- README.md
> added Product Backlog

- README.md
added Empathy-Mapping for every user persona
> added Empathy-Mapping

- README.md
Se agrega el Journey Map completo para los Users Personas correspondientes
> Agreggate Journey Map

- README.md
added context, container, and components diagrams
> added software architecture context diagram

- README.md
This confirmation presents wireframes for the web application, describing the user's journey
> added web aplications wireframes

- README.md
This commit introduces wireflow diagrams for the web application
> added Web applications wireflow diagrams

- README.md
Add Class-Diagrams using bounded context.
> Add Class-Diagrams

- README.md
Add class dictionary using atributes of clases.
> Add Class-Dictionary

- README.md
Add software configuration management using the technologies such as HTML, CSS, TYPESCRIPT, MARKDOWN, VSCODE, ETC.
> Add Software Configuration Management

- README.md
> added Source Code Management

- README.md
Software Deployment Configuration
> added Software Deployment Configuration

- README.md
Development Evidence for Sprint Review
> added Development Evidence for Sprint Review

- README.md
> added LeanUX

- README.md
> Update Student Outcome 3

- README.md
Added Web Applications Mock-ups to showcase user flows and UI designs
> added Web Applications Mock-ups

- README.md
introduces detailed user flow diagrams that outline the step-by-step journey through key features of the web application.
> added User Flow Diagrams

- README.md
> add-entrevistas

- README.md
fixed Lean UX Problem Statements using the feedback
> fixed Lean UX Problem Statements

- README.md
fixed Domain-Driven Software Architecture corrections
> fixed Domain-Driven Software Architecture

- README.md
> added sprint 2
